//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamlDS.Itk.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamlDS.Itk.Resources.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Action_About {
            get {
                return ResourceManager.GetString("Action_About", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Action_Add {
            get {
                return ResourceManager.GetString("Action_Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Action_Apply {
            get {
                return ResourceManager.GetString("Action_Apply", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Action_Close {
            get {
                return ResourceManager.GetString("Action_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Action_Copy {
            get {
                return ResourceManager.GetString("Action_Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Action_Cut {
            get {
                return ResourceManager.GetString("Action_Cut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string Action_DeleteAll {
            get {
                return ResourceManager.GetString("Action_DeleteAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Action_Edit {
            get {
                return ResourceManager.GetString("Action_Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Action_Exit {
            get {
                return ResourceManager.GetString("Action_Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit Fullscreen.
        /// </summary>
        public static string Action_ExitFullscreen {
            get {
                return ResourceManager.GetString("Action_ExitFullscreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Action_Export {
            get {
                return ResourceManager.GetString("Action_Export", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string Action_Fullscreen {
            get {
                return ResourceManager.GetString("Action_Fullscreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Action_Help {
            get {
                return ResourceManager.GetString("Action_Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Action_Home {
            get {
                return ResourceManager.GetString("Action_Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Action_Import {
            get {
                return ResourceManager.GetString("Action_Import", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Action_Maximize {
            get {
                return ResourceManager.GetString("Action_Maximize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Action_Minimize {
            get {
                return ResourceManager.GetString("Action_Minimize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Action_New {
            get {
                return ResourceManager.GetString("Action_New", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Action_No {
            get {
                return ResourceManager.GetString("Action_No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Action_OK {
            get {
                return ResourceManager.GetString("Action_OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Action_Open {
            get {
                return ResourceManager.GetString("Action_Open", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Action_Paste {
            get {
                return ResourceManager.GetString("Action_Paste", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Action_Quit {
            get {
                return ResourceManager.GetString("Action_Quit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Action_Redo {
            get {
                return ResourceManager.GetString("Action_Redo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Action_Refresh {
            get {
                return ResourceManager.GetString("Action_Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Action_Reload {
            get {
                return ResourceManager.GetString("Action_Reload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Action_Remove {
            get {
                return ResourceManager.GetString("Action_Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Action_Restore {
            get {
                return ResourceManager.GetString("Action_Restore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string Action_SaveAll {
            get {
                return ResourceManager.GetString("Action_SaveAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string Action_SaveAs {
            get {
                return ResourceManager.GetString("Action_SaveAs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Action_Search {
            get {
                return ResourceManager.GetString("Action_Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Action_SelectAll {
            get {
                return ResourceManager.GetString("Action_SelectAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Action_Settings {
            get {
                return ResourceManager.GetString("Action_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Action_Undo {
            get {
                return ResourceManager.GetString("Action_Undo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Action_Yes {
            get {
                return ResourceManager.GetString("Action_Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string Action_ZoomIn {
            get {
                return ResourceManager.GetString("Action_ZoomIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string Action_ZoomOut {
            get {
                return ResourceManager.GetString("Action_ZoomOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset Zoom.
        /// </summary>
        public static string Action_ZoomReset {
            get {
                return ResourceManager.GetString("Action_ZoomReset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Common_All {
            get {
                return ResourceManager.GetString("Common_All", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Common_Custom {
            get {
                return ResourceManager.GetString("Common_Custom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Common_Default {
            get {
                return ResourceManager.GetString("Common_Default", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Common_None {
            get {
                return ResourceManager.GetString("Common_None", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Common_Unknown {
            get {
                return ResourceManager.GetString("Common_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Label_Author {
            get {
                return ResourceManager.GetString("Label_Author", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Label_Created {
            get {
                return ResourceManager.GetString("Label_Created", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Label_Modified {
            get {
                return ResourceManager.GetString("Label_Modified", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Label_Path {
            get {
                return ResourceManager.GetString("Label_Path", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Label_Size {
            get {
                return ResourceManager.GetString("Label_Size", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Label_Theme {
            get {
                return ResourceManager.GetString("Label_Theme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Label_Type {
            get {
                return ResourceManager.GetString("Label_Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Label_Version {
            get {
                return ResourceManager.GetString("Label_Version", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Menu_Window {
            get {
                return ResourceManager.GetString("Menu_Window", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Status_Canceled {
            get {
                return ResourceManager.GetString("Status_Canceled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Status_Completed {
            get {
                return ResourceManager.GetString("Status_Completed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Status_Failed {
            get {
                return ResourceManager.GetString("Status_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Status_Loading {
            get {
                return ResourceManager.GetString("Status_Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Status_Processing {
            get {
                return ResourceManager.GetString("Status_Processing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string Status_Saving {
            get {
                return ResourceManager.GetString("Status_Saving", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string Time_Now {
            get {
                return ResourceManager.GetString("Time_Now", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Time_Today {
            get {
                return ResourceManager.GetString("Time_Today", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string Time_Tomorrow {
            get {
                return ResourceManager.GetString("Time_Tomorrow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Time_Yesterday {
            get {
                return ResourceManager.GetString("Time_Yesterday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string Unit_Bytes {
            get {
                return ResourceManager.GetString("Unit_Bytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string Unit_GB {
            get {
                return ResourceManager.GetString("Unit_GB", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string Unit_KB {
            get {
                return ResourceManager.GetString("Unit_KB", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string Unit_MB {
            get {
                return ResourceManager.GetString("Unit_MB", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        public static string Unit_TB {
            get {
                return ResourceManager.GetString("Unit_TB", resourceCulture);
            }
        }
    }
}
